version: '3.0'
services:
  test:
    image: dockervize/test
    container_name: dockervize-test
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run test

volumes:
  node_modules:
